package tmmsystem.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tmmsystem.entity.*;
import tmmsystem.repository.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

@Service
public class BomBackfillService {
    private static final Logger log = LoggerFactory.getLogger(BomBackfillService.class);

    private final ProductRepository productRepository;
    private final BomRepository bomRepository;
    private final BomDetailRepository bomDetailRepository;
    private final MaterialRepository materialRepository;

    public BomBackfillService(ProductRepository productRepository,
            BomRepository bomRepository,
            BomDetailRepository bomDetailRepository,
            MaterialRepository materialRepository) {
        this.productRepository = productRepository;
        this.bomRepository = bomRepository;
        this.bomDetailRepository = bomDetailRepository;
        this.materialRepository = materialRepository;
    }

    /**
     * Scans all products and creates a default BOM if none exists.
     * Scheduled to run daily at midnight.
     */
    @Scheduled(cron = "0 0 0 * * ?")
    @Transactional
    public void backfillMissingBoms() {
        log.info("Starting BOM backfill process...");
        List<Product> products = productRepository.findAll();
        int createdCount = 0;

        // Find a default material to use
        Material defaultMaterial = findDefaultMaterial();
        if (defaultMaterial == null) {
            log.warn("No materials found in database. Cannot backfill BOMs.");
            return;
        }

        for (Product product : products) {
            if (bomRepository.findActiveBomByProductId(product.getId()).isEmpty()) {
                createDefaultBom(product, defaultMaterial);
                createdCount++;
            }
        }

        if (createdCount > 0) {
            log.info("Backfilled BOMs for {} products.", createdCount);
        } else {
            log.info("All products already have active BOMs.");
        }
    }

    private Material findDefaultMaterial() {
        // Try to find something that looks like "Sợi" or "Cotton"
        List<Material> materials = materialRepository.findAll();
        return materials.stream()
                .filter(m -> m.getName().toLowerCase().contains("sợi") || m.getName().toLowerCase().contains("cotton"))
                .findFirst()
                .orElse(materials.stream().findFirst().orElse(null));
    }

    private void createDefaultBom(Product product, Material material) {
        Bom bom = new Bom();
        bom.setProduct(product);
        bom.setVersion("v1-auto");
        bom.setVersionNotes("Auto-generated by system to prevent missing BOM errors");
        bom.setActive(true);
        bom.setEffectiveDate(LocalDate.now());

        Bom savedBom = bomRepository.save(bom);

        BomDetail detail = new BomDetail();
        detail.setBom(savedBom);
        detail.setMaterial(material);
        // Default quantity: 1.0 or based on product weight if available
        BigDecimal quantity = BigDecimal.ONE;
        if (product.getStandardWeight() != null && product.getStandardWeight().compareTo(BigDecimal.ZERO) > 0) {
            // Convert grams to kg (assuming material unit is kg)
            quantity = product.getStandardWeight().divide(BigDecimal.valueOf(1000));
        }
        detail.setQuantity(quantity);
        detail.setUnit(material.getUnit());
        detail.setStage("WARPING"); // Default stage
        detail.setOptional(false);
        detail.setNotes("Auto-generated default material");

        bomDetailRepository.save(detail);
        log.info("Created auto-BOM for product: {} (ID: {})", product.getName(), product.getId());
    }
}
